### ISSUE TITLE
`pb_upload()` should pass dots `...` to `pb_release_create()`

### ISSUE THREAD

**Issue by mrcaseb** [ropensci/piggyback#104]
AS far as I understand, `pb_upload()` checks if a release exists and offers the option to create it if it doesn't exist. 

However, there is no way to pass args to `pb_release_create()` so a release created with `pb_upload()` will always use defaults of `pb_release_create()`. 

I think it would make sense to pass dots to `pb_release_create()`

**Comment by tanho63** [comment]
thinking about this more, I think I'd prefer to see the interactive release creation removed altogether rather than adding _more_ args to `pb_release_create()`, and instead just erroring with a useful error message if the release doesn't exist - less "magical" experience that way

**Comment by cboettig** [comment]
yup, makes sense to me.
