### ISSUE TITLE
Chinese localization documentation Authorization

### ISSUE THREAD

**Issue by Liber1917** [ropensci/piggyback#108]
I am a student from Northeastern University in China who is highly interested in your project. I find it beneficial to be able to upload my project archives and demo videos WITHOUT git LFS. Obtaining your permission to promote your influence would be greatly appreciated.

**Comment by tanho63** [comment]
Glad to hear that you are enjoying using the piggyback package! You're very welcome to share and promote usage of the package in any language (including Chinese/Mandarin/Cantonese), and can cite it in formal/academic publications etc with the output of `citation("piggyback")` e.g.

```r
citation("piggyback")
#> To cite package ‘piggyback’ in publications use:
#>   
#>   Boettiger C, Ho T (2023). _piggyback: Managing Larger Data on a GitHub Repository_. R
#> package version 0.1.5, <https://github.com/ropensci/piggyback>.
#> 
#> A BibTeX entry for LaTeX users is
#> 
#> @Manual{,
#>   title = {piggyback: Managing Larger Data on a GitHub Repository},
#>   author = {Carl Boettiger and Tan Ho},
#>   year = {2023},
#>   note = {R package version 0.1.5.9002},
#>   url = {https://github.com/ropensci/piggyback},
#> }
```

I don't believe ROpenSci is currently supporting localization/translation projects for Mandarin/Cantonese per [this list](https://github.com/ropensci-review-tools/translation_guide#languages-with-active-projects), so it seems unlikely we'll be able to take on any sort of Chinese-language localization projects at the current time. If this changes, we'd be glad to welcome PRs! You can read more about ROpenSci's translation guide/policies here: <https://translationguide.ropensci.org/>.
