### ISSUE TITLE
change folder structure when uploading to github

### ISSUE THREAD

**Issue by cmzambranat** [ropensci/piggyback#18]
Hi,
Not sure if this is an issue with `piggyback` or this is the way `Releases` in github works. 

I have a few files that I've been syncing with `piggyback`. Below is the structure on my *original* repo:
```
├── data
│   └── zip
│       ├── file1.zip
│       └── file2.zip 
```

When I upload the files into github I get the following list of files:

`default.2fdata.2fzip.2ffile1.zip 363 MB`
`default.2fdata.2fzip.2ffile2.zip 443 MB`

If I clone the repo then the new folder structure is like this

```
├── data
│   └── zip
│       ├── default
│       │   └── data
│       │       └── zip
│       │           ├── file1.zip
│       │           └── file2.zip
```

As you can see now we have additional folders that were not present in the original repo. Is this a bug in `piggyback`? Perhaps need to change some settings in github?

thanks!

**Comment by cboettig** [comment]
hmm, that doesn't look good!  How are you uploading your files? (e.g. specifying path manually or using `pb_track()?`

Is your repo set up as an RStudio project? (i.e. does it have a `reponame.Rproj` file?

**Comment by cmzambranat** [comment]
I uploaded the files using:

```
pb_upload("file1.zip", 
          repo = "cmzambranat/repo", 
          tag = "v1.0.0")
```
I used `pb_track("*.zip")` right after the above code. Does the order matter?
I have a RStudio project, and this is the text inside:

```
RestoreWorkspace: Default
SaveWorkspace: Default
AlwaysSaveHistory: Default
```

This seems to be problem, but not sure how to procede.

**Comment by cboettig** [comment]
That's strange.  I can't replicate what you are seeing.  Is your working directory set to `data/` then when you run:

```
pb_upload("file1.zip", 
          repo = "cmzambranat/repo", 
          tag = "v1.0.0")
```

piggyback should basically use the relative path that you used in the upload.  

Can you delete these files from your GitHub assets (you can do this with `piggyback` or simply in the browser through GitHub release menu) and test again to confirm?

**Comment by cmzambranat** [comment]
I was able to replicate the problem. Below is the code I used. I thought the problem was the the package `here`, so I tested without using `here` and I got the same problem.

```
# Create new release in GitHub
pb_new_release("cmzambranat/test_piggy/", "test")

# Upload
pb_upload(here("output/zip/file3.zip"), 
          repo = "cmzambranat/test_piggy", 
          tag = "test")
```

No using `here`

```
pb_upload("output/zip/file2.zip", 
          repo = "cmzambranat/test_piggy", 
          tag = "test2")
```

Repo is public here: https://github.com/cmzambranat/test_piggy

**Comment by cboettig** [comment]
@cmzambranat I don't see anything wrong in your latest example. What is the problem to which you refer?

 In your replication above, you upload the file with the path `output/zip/file3.zip`.  I we ask `piggyback` where the file is, we see what we expect:

```
>  pb_list("cmzambranat/test_piggy", "latest")
                 file_name size           timestamp   tag       owner       repo
1       output/mtcarsv2.xz  604 2018-10-23 17:02:50 test3 cmzambranat test_piggy
2 output/zip/mtcars.tsv.xz  604 2018-10-23 17:00:35 test3 cmzambranat test_piggy
```

If  I start a new project i a fresh directory, and do `pb_dowload`:

```
pb_download(repo = "cmzambranat/test_piggy")
✔ Setting active project to '/Users/cboettig/Documents/espm-157/test'
downloading mtcarsv2.xz ...
  |============================================================================================| 100%
downloading mtcars.tsv.xz ...
  |============================================================================================| 100%
````

with the same directory structure as you expected:

```r
fs::dir_ls(recursive = TRUE)
output                   output/mtcarsv2.xz       output/zip               output/zip/mtcars.tsv.xz 
test.Rproj     
```

What do you see?  This all looks good to me.  (like you say, same thing with or without `here`.)  What is wrong?  

Note: Yes, the path names look funny on the asset itself, because we're not allowed to have `/` characters in the filenames of github assets 🙃 .  But piggyback will always pretty these up when it uses or displays them.

**Comment by cmzambranat** [comment]
@cboettig thank you so much for taking the time to answer my question. I deleted the repo that was giving me the problem and started from scratch again and now everything works! To be honest I don't know what was the problem. I just follow the instructions again and it works!

Again thank you for your time and for the great work with `piggyback`!
