### ISSUE TITLE
Unable to overwrite/delete files that were only partially uploaded

### ISSUE THREAD

**Issue by jeffreyhanson** [ropensci/piggyback#19]
Thank you so much for developing the _piggyback R_ package - it's absolutely fantastic and a game-changer for using GitHub with large datasets! 

We've been using piggyback to host assets (e.g. maps, graphs, pdf files) for a GitHub project (https://github.com/bird-team/brisbane-bird-atlas), and have started running into problems when we try uploading ~500 pdf files at a time. Specifically, the issue we are encountering is that sometimes the upload process fails for a single file (in other words, the upload terminates prematurely -- perhaps due to an unreliable internet connection). If this happens, we are unable to upload the file again using `pb_upload` (even with `overwrite = TRUE`), and we are also unable to delete corrupt/partially uploaded file either using `pb_delete`. This is not too much of a problem when just working with <10 files because we can manually delete the corrupt/partially uploaded file via the online GitHub web interface, but it causes problems when working with >100 files. Unfortunately, we cannot simply zip the files into an archive because we need to make each file downloadable separately. 

To replicate the problem, please follow the instructions below.

```
# load package
library(piggyback) # version 0.0.8

# set variables - you will need to change this to your own repo for this work
repo_name <- "bird-team/brisbane-bird-atlas"
release_name <- "v.0.0.1"

# find file to upload
## here we use the data file in the rnaturalearthhires package
path <- file.path(system.file(package = "rnaturalearthhires"), "data", "Rdata.rdb")

# upload the file
## remember to terminate this early by stopping the code (e.g. pressing esc or crtl+c)
result <- pb_upload(path, repo = repo_name, tag = release_name, name = "test.rdb")

# now try to upload again
result2 <- pb_upload(path, repo = repo_name, tag = release_name, name = "test.rdb", 
                     overwrite = TRUE)

## you should recieve this error:
## Error in pb_upload_file(f, repo, tag, name, overwrite, use_timestamps,  : 
## Unprocessable Entity (WebDAV; RFC 4918) (HTTP 422).

# now let's list the files in the release
pb_list(repo = repo_name, tag = release_name)
## you should see that this file is not listed in the output

# now let's try deleting the file - but this doesn't work
pb_delete("test.rdb", repo = repo_name, tag = release_name)
## test.rdb not found on GitHub
## NULL
```

I've also included this screenshot showing that the partially uploaded file is "present" on GitHub, even if it's not available under `pb_list`.

![screenshot_20181219_110210](https://user-images.githubusercontent.com/3610005/50192427-fc49c880-037d-11e9-8ffc-6e2e89f6264c.png)

I apologise if this issue is beyond the scope of this package, and instead is a problem with the GitHub API itself. I did try playing around with the _gh R_ package but I didn't have any luck.

**Comment by cboettig** [comment]
Thanks for the kind words and the bug report.  Yes, I've observed this once or twice myself as well, though haven't figured out a scriptable solution.  As you've noted, this creates a failed-upload object that can be seen, detected and deleted manually using the web interface, but seems to be invisible to the API(?)  I'd like to resolve this, but am worried that this may be an intrinsic limitation/bug on the GitHub API side.  

`pb_delete` checks for the file in `pb_list` first.  I wonder if it could successfully delete the failed file if we skipped that check?  Were you able to delete either the bad file or any other files with your direct API calls via `gh`?

**Comment by jeffreyhanson** [comment]
I had another attempt using the _gh R_ package and I've managed to find a way to find the GitHub ID for a "partially uploaded file" which suggests that we might have a method for programmatically deleting the files.

```
# load package
library(gh)

# define function to delete file using name
pb_delete2 <- function(file = NULL,
                       repo = guess_repo(),
                       tag = "latest",
                       .token = get_token()) {

# get release metadata
m <- gh("/repos/:owner/:repo/releases/tags/:tag", owner = "bird-team", 
        repo = "brisbane-bird-atlas", tag = "v.0.0.1")

# get asset metadata
a <- gh("/repos/:owner/:repo/releases/:release_id/assets", owner = "bird-team", 
        repo = "brisbane-bird-atlas", release_id = m$id)

# extract asset names and ids
do.call(rbind, lapply(lapply(a, `[`, c("name", "id")), as.data.frame))
## this should print out a table that includes the ID for "test.rdb", 
## which is a partially uploaded file
``` 

I think the problem is that the partially uploaded files aren't included when using the `/repos/:owner/:repo/releases` call to the GH API (which is what AFAIK piggyback is using at the moment?), and instead we have to specify that the want the asset metadata for a particular release to get these files included, i.e. `/repos/:owner/:repo/releases/:release_id/assets`. Is that correct?

I'll see if I can put together a quick PR that updates `piggyback:::release_info` to use the `"/repos/:owner/:repo/releases"` API call to get all the release information, and then loop over each release and manually replace the "assets" element with results from the  `/repos/:owner/:repo/releases/:release_id/assets` API call. Then `pb_delete` should "just work" (hopefully) because it gets the ID for the partially uploaded files? What do you think?

**Comment by jeffreyhanson** [comment]
It looks like updating `pb_info` to include information on the partially uploaded files means that we don't even need to delete the partially uploaded file prior to attempting to a reupload. If we set `use_timestamps = FALSE` and `overwrite=TRUE` then we can just overwrite the file directly. For example,

```
# install fork
devtools::install_github("jeffreyhanson/piggyback@deletefail")

# load package
library(piggyback)

# set variables - you will need to change this to your own repo for this work
repo_name <- "bird-team/brisbane-bird-atlas"
release_name <- "v.0.0.1"

# find file to upload
## here we use the data file in the rnaturalearthhires package
path <- file.path(system.file(package = "rnaturalearthhires"), "data", "Rdata.rdb")

# upload the file
## remember to terminate this early by stopping the code (e.g. pressing esc or crtl+c)
result <- pb_upload(path, repo = repo_name, tag = release_name, name = "test.rdb")

# now try to upload again - and we don't even need to delete it!
result2 <- pb_upload(path, repo = repo_name, tag = release_name, name = "test.rdb", 
                                  use_timestamps = FALSE, overwrite = TRUE)
```
