### ISSUE TITLE
Consider heuristics in `guess_repo()`

### ISSUE THREAD

**Issue by kevinykuo** [ropensci/piggyback#31]
Currently, `guess_repo()` returns all remotes. This means that in most collaborative settings where users have e.g. `upstream` and `origin` set up, the functions depending on `guess_repo()` won't work unless `repo` is explicitly provided. It might make sense to default to the `upstream` remote if it exists?

**Comment by cboettig** [comment]
👍 Yeah, that makes sense to me.  Want to send a PR for this?

**Comment by kevinykuo** [comment]
Yep would be happy to send a PR
