### ISSUE TITLE
Deprecated access token in the query  

### ISSUE THREAD

**Issue by lolow** [ropensci/piggyback#36]
Follow-up of my post in this issue: https://github.com/r-lib/gh/issues/106

Access token in the query is deprecated by github, as it should be send in the HTTP header (https://developer.github.com/changes/2019-11-05-deprecated-passwords-and-authorizations-api/#authenticating-using-query-parameters). 

I thought it was a `gh` issue, but as pointed by @gaborcsardi in https://github.com/r-lib/gh/issues/106#issuecomment-582346887, this might be fixed in `piggyback`.

**Comment by cboettig** [comment]
Thanks for the report, looks like a straight-forward fix.  PR welcome or I'll find some time to take a stab at that soon.

p.s. have you seen `pins` from RStudio yet?  https://pins.rstudio.com.  Has a somewhat different take on just how a GitHub storage backend should work, but looks very intriguing!

**Comment by lolow** [comment]
ok, I will see if I can help here. And thanks for pointing out `pins` that I did not know and it looks rather versatile. But, for the moment, I will stick to `piggyback`.

**Comment by cboettig** [comment]
Closed by #39
