### ISSUE TITLE
Push to CRAN

### ISSUE THREAD

**Issue by 1beb** [ropensci/piggyback#41]
The current version 0.0.11 is on CRAN but does not include the updates to authorization. Looks like the version needs a bump and a new push to CRAN needs to happen.

**Comment by cboettig** [comment]
thanks for the ping, I'll prep a release.  (I think we do have a few other outstanding issues due to API changes but at least we can get the latest version here up to CRAN).

**Comment by cboettig** [comment]
done at last, along with several other changes, see NEWS.md
