### ISSUE TITLE
pb_track has gone?

### ISSUE THREAD

**Issue by Skourtis** [ropensci/piggyback#51]
has pb_track been removed? Has it been replaced by something else or is there a new way to add items to gitignore?

Thank you!

**Comment by cboettig** [comment]
Apologies for the lack of proper release notes here! 

 `pb_track()` was originally intended to accompany `pb_push()` and `pb_pull()`, mimicking the `git` syntax.  The latter two have been removed for some time, as we found it was generally better to rely on `pb_upload()` and `pb_download()` which take vectors of files to be moved as explicit arguments.  For a while we left `pb_track()`, which could be used as a short-hand to generate a file list, e.g. `pb_track() %>% pb_upload()` was essentially the same as using `fs::dir_ls()` to list the desired file patterns (e.g. `*.csv` etc) to be uploaded.  A user could still maintain an index file of what should be tracked in any way they wish, but at this point `pb_track()` seemed almost miss-leading -- it doesn't really guarantee that you track anything, it just created a list of such files (and added them to .gitignore).

There are already many ways to add files to gitignore (`usethis::use_git_ignore`, RStudio git GUI, etc etc), so providing that role seems out-of-scope here.  

Let me know if this doesn't make sense, happy to reconsider!
