### ISSUE TITLE
pb_new_release target_commitish not working

### ISSUE THREAD

**Issue by tanho63** [ropensci/piggyback#58]
Video here: https://streamable.com/456a6o

I'm not "quite" sure what's going on but I believe it's because pb_info() calls pb_new_release() backend? Looking into this now

**Comment by tanho63** [comment]
So the primary difference between the outer and inner calls is target_commitish in payload, the first resulting in a POST error 422 
![image](https://user-images.githubusercontent.com/38083823/156407134-54c2ebf5-a7f8-4536-9e11-9ecb7a156fa0.png)

**Comment by tanho63** [comment]
Okay, so the problem is that target_commitish must refer to the full SHA and not an abbreviated one as displayed by GitHub etc. 

Using the full SHA works as expected: 
![image](https://user-images.githubusercontent.com/38083823/156409132-5a77a636-5786-4d3d-bff2-b35a9d7ba549.png)

I think a more natural behaviour for pb_new_release is to use `httr::stop_for_status()` so that it stops if the POST fails and reports the error, rather than only warning for status if verbose

**Comment by cboettig** [comment]
Thanks for digging into this! Agreed. A PR would be welcome!

**Comment by tanho63** [comment]
Closing this issue since it's not in piggyback's scope to resolve short-hashes on behalf of the GH API
