### ISSUE TITLE
pb_list() should not offer to create a new release if no releases are found

### ISSUE THREAD

**Issue by tanho63** [ropensci/piggyback#60]
I think pb_info() does too much right now and would be less surprising if it only offered to create a new release in specific situations, e.g. when trying to upload something. It doesn't make sense if I'm querying whether there is release data (e.g. `pb_list()`) 

```
R> piggyback::pb_list("tanho63/tanho63")
No releases found would you like to create one? (yes/no/cancel) no
```

I can make a PR to add a parameter to pb_info so that it can be configured to prompt you (and default to offer creation since that's the current default and would maintain backcompat)

**Comment by cboettig** [comment]
yeah I agree :100: .  a PR for this would be excellent.  (and I'll plan to submit a CRAN release once we resolve this and #61 )
