### ISSUE TITLE
pb_list() will soon fail if multiple tags are specified

### ISSUE THREAD

**Issue by tanho63** [ropensci/piggyback#61]
If I'm querying a repository for files attached to multiple tags, it currently "works" in that it returns the expected dataframe but has the following warnings:
```
R> x <-   piggyback::pb_list(repo = "nflverse/nflverse-data", tag = c("pbp","player_stats"))
Warning messages:                                
1: In if (tag == "latest") { :
  the condition has length > 1 and only the first element will be used
2: In if (tag %in% info$tag) { :
  the condition has length > 1 and only the first element will be used
```

These warnings will soon be an error as of R 4.2+ https://twitter.com/henrikbengtsson/status/1496597313510273026?s=20 - so properly supporting vectorized tags would be useful! 

I think this again refers to `pb_info()` related issues.

**Comment by cboettig** [comment]
thanks good catch.  Would you be able to send a PR for this one?

**Comment by tanho63** [comment]
Yep, can do!
