### ISSUE TITLE
Can not see uploaded file

### ISSUE THREAD

**Issue by PMassicotte** [ropensci/piggyback#69]
First, thank you for the package, it will help me a lot for my quest of reproducible science.
I created a repo to experiment with `piggyback`: https://github.com/PMassicotte/learn-piggyback/releases/tag/v0.1.5. I am using the following code to upload a simple CSV file.

``` r
library(piggyback)

pb_new_release(tag = "v0.1.5", repo = "PMassicotte/learn-piggyback/")
#> ✔ Created new release "v0.1.5".

tmpfile <- tempfile(fileext = ".csv.gz")
readr::write_csv(mtcars, tmpfile)

pb_upload(tmpfile, repo = "PMassicotte/learn-piggyback/")
#> ℹ Uploading 'file841a2b175d0a.csv.gz' ...
#>   |                                                                              |                                                                      |   0%  |                                                                              |======================================================================| 100%
```
However, I can not see the file in any of the test release I created. Maybe I missed something?

![image](https://user-images.githubusercontent.com/4519221/169040097-d659e4bb-8c6c-40e4-b6d1-2939ef754ce1.png)

Thanks in advance for any guidance.

Philippe

<sup>Created on 2022-05-18 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

**Comment by tanho63** [comment]
@pmassicotte you didn't specify the release to upload to so it's uploading to "latest" by default I think https://github.com/PMassicotte/learn-piggyback/releases/tag/latest

**Comment by PMassicotte** [comment]
oh, I see. I completely missed it. Thank you @tanho63 !
