### ISSUE TITLE
Subset issues when using `piggyback` and `renv`

### ISSUE THREAD

**Issue by PMassicotte** [ropensci/piggyback#70]
I have found multiple issues when using `piggyback` with `renv` enabled project that are likely linked to how subset works for `tibble` vs `data.frame`. 

For example, the function `pb_releases()` do not work when `renv` is enabled. This is occurring here: https://github.com/ropensci/piggyback/blob/4b7cdb9f45af1440f0cb6a0916c4f8b6553e60e5/R/utils.R#L69

With `renv` enabled, `remotes[remotes[["name"]] == remote, "url"]` is a `character`. Hence, using `[["url"]]` does not work. When `renv` is *not* enabled, the same is a `tibble` and can be subsetted using `[["url"]]`.

I have made an animated GIF that hopefully show the problem clearly. You can see that `pb_releases()` stops working when `renv` is activated. When `renv` is deactivated, `pb_releases()` works again.

![Peek 2022-05-18 13-40](https://user-images.githubusercontent.com/4519221/169107732-fbd782e5-0560-4385-b25c-7664d1149588.gif)

Note that the same problem occurs for some other functions of the packages.

**Comment by tanho63** [comment]
the problem is specifically `guess_repo()` right? not `pb_releases()`?

**Comment by PMassicotte** [comment]
Well, as I understand, `pb_releases()` calls `guess_repo()`, but yes is it occurring specifically in `guess_repo()`.

**Comment by tanho63** [comment]
Interesting! Can you try using `gh::gh_tree_remote()` as the argument to repo? Might be an easy drop-in fix

**Comment by PMassicotte** [comment]
I have tried this but no luck:

```r
> pb_releases(repo = gh::gh_tree_remote())
Error in strsplit(repo, "/") : non-character argument
```

**Comment by tanho63** [comment]
Oh. Duh, it returns a list. But at least it returns something! I suspect the problem is that renv only caches the import dependencies so when guess_repo tries to use gert it fails somehow.

**Comment by PMassicotte** [comment]
If I install `tibble` in the project (which is afterwards cached by `renv`) it works. So it looks like that

https://github.com/ropensci/piggyback/blob/4b7cdb9f45af1440f0cb6a0916c4f8b6553e60e5/R/utils.R#L51

returns a `tibble`. Since it was not needed in my project, it simply returns a dataframe.

Then, subsetting a data.frame here:

```r
remotes[remotes[["name"]] == remote, "url"][["url"]]
```
does not work since `remotes[remotes[["name"]] == remote, "url"]` returns a `character` rather than a `tibble` if `tibble` is loaded.

**Comment by tanho63** [comment]
Oh so it just needs to be remotes$url[remotes$name == remote] then…

I wonder if that’s better or worse than shortening dependencies and using gh here for that too

**Comment by PMassicotte** [comment]
> Oh so it just needs to be remotes$url[remotes$name == remote]] then…

Exactly!

> I wonder if that’s better or worse than shortening dependencies and using gh here for that too

Good question :)
