### ISSUE TITLE
`pb_upload_file` argument `show_progress` should default to `interactive()` 

### ISSUE THREAD

**Issue by mrcaseb** [ropensci/piggyback#72]
https://github.com/ropensci/piggyback/blob/2ab52a08a868db4d9ee7aa9b7a123652fa07689d/R/pb_upload.R#L89

`show_progress` currently reads the option "piggyback.verbose" which is perfectly fine in my opinion. However, it defaults to `TRUE` which results in console output in batch mode if the option is not set. I would suggest `interactive()` as default.

cc: @tanho63

**Comment by mrcaseb** [comment]
I think this also applies to 

https://github.com/ropensci/piggyback/blob/f54d041123378b61e9da60f0cd0b373ce5e2676e/R/pb_download.R#L35

**Comment by tanho63** [comment]
Oh that would be a good idea!

**Comment by cboettig** [comment]
Thanks @mrcaseb -- would you like to send us a PR for this?

**Comment by mrcaseb** [comment]
> Thanks @mrcaseb -- would you like to send us a PR for this?

Done in #74 but now I realize that @tanho63 was already working on it, sorry Tan
