### ISSUE TITLE
minor: use `gh::gh_tree_remote()` in guess_repo() instead of gert

### ISSUE THREAD

**Issue by tanho63** [ropensci/piggyback#80]
This could be a good improvement to the code since it would: 

a) ensure that the repository is a GitHub repository (where currently it might still use a non-github one)
b) eliminate the gert suggested dependency and simplify the code a lot (just wrap one function, basically)

Differences to current implementation: it would choose origin by default rather than upstream. This might be an okay change since users who have both an origin and an upstream configured would probably be unlikely to have push permissions to upstream. It'll also warn the users by default.

**Comment by cboettig** [comment]
yup, definitely a nice change. `gert` is a somewhat heavy dependency for adding rather little here too.  doesn't seem likely to have any really adverse changes.
