### ISSUE TITLE
[feature] add functions to update/delete releases?

### ISSUE THREAD

**Issue by tanho63** [ropensci/piggyback#81]
It might be a good idea to fully flesh out release management (we have "create" already, it could be useful to have "update" to update the details etc and "delete" to prune them)

**Comment by cboettig** [comment]
yeah, interesting idea.  I'm reluctant to duplicate `gh` wrapping granular functions of the GitHub API, but it does make sense that users could do the necessary piggyback things within piggyback.  It's definitely natural to have inverse functions though.  

Actually realizing I wasn't good about sticking with verb names in the current API (`pb_new_release()` isn't a verb with an obvious inverse like create() / delete(), similarly it's not always obvious from the fn name what fns list information and what perform actual PUT/POST changes....  Could overload some of the existing API with additional functionality, though that's usually a poor choice.  Anyway, I'm open for ideas.  For now I think something like `pb_delete_release()` might be the natural inverse of `pb_new_release()` ?

**Comment by tanho63** [comment]
Yeah, `pb_delete_release()` could make sense, as could renaming the functions to `pb_release_create` and `pb_release_delete` (and aliasing `pb_new_release` to call `pb_release_create`)

I can start fleshing out some of the delete code anyway and happy to defer to opinions on naming
